### ISSUE TITLE
Request - Deactivate Speaker on busylight

### ISSUE THREAD

**Issue by djhalla** [Dcnigma/Bizylight-3XC-integration#1]
Hi!

First of all, thank you for this.
Its works like a charm, we are using this in a office, without any issue at all.
But, it would be nice if you could release the function to enable or disable the internal speaker on the busylight. Since we are in an open office location, the ringing is very annoying. We are using the Kuando's Omega Busylight.

Would it be possible to deactivate the build in speaker?

**Comment by Bejlem** [comment]
Hello djhalla,
I figured out how to change the code to achieve exactly this:
Change the file 'frmMain.Designer.cs' in the line 223 to:
    this.tbVolume.Value = 0;
So basically you just have to delete the 5 in that line and then just re-compile the lib. That's basically it.
